package com.arthur.idc.aspects.audit.aop;

import com.arthur.idc.aspects.audit.entity.ResOperLog;

public interface ResOperLogGenerator {

	/**
	 * Generate log info before the listened operation invoked.
	 * Just record the info to prevent arguments reference changed after invoking.
	 * @param arguments
	 * @return log info of the operation.
	 */
	ResOperLog generateLogBeforeInvoke(Object[] arguments);
	
	/**
	 * Warp the log info generated by the generateLogBeforeInvoke method,
	 * if the listened operation doesn't invoke successfully,
	 * wrapLogAfterInvoke method will return null. 
	 * @param arguments
	 * @param returnValue
	 * @param log
	 * @return Wrapped log, or null if the listened operation doesn't invoke successfully.  
	 */
	ResOperLog wrapLogAfterInvoke(Object[] arguments,Object returnValue,ResOperLog log);
	
}
