spring:
  application:
    name: UserCredits-Service
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
  #    metadataMap:
  #      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones:
      default: http://localhost:8761/eureka