server:
  port: 9090

spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: gateway
          uri: "http://localhost:9500"
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1



management:
  endpoints:
    web:
      expoure:
        include: "*"




logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

