spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/userinfo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
