spring:
#  application:
#    name: UserCredits-Service
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.78:3306/mydb
    username: root
    password: root
#  h2:
#    console:
#      enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: update
#mybatis:
#  mapper-locations: classpath*:mappers/*.xml
#    show-sql: true